/**
 * Promise.reject() 方法 返回 一个带有拒绝原因的 Promise 对象。
 */

/*
function resolved(result) {
  console.log('Resolved');
}

function rejected(result) {
  console.error(result);
}

Promise.reject(new Error('fail')).then(resolved, rejected);
// expected output: Error: fail
* */
